[package]
name = "sram22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
magic_vlsi = { path = "../magic_vlsi" }
micro_hdl = { path = "../micro_hdl" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
log = "0.4"
env_logger = "0.9"
